export { default as HomePage } from './HomePage/HomePage';
export { default as ContactUsPage } from './ContactUsPage/ContactUsPage';
export { default as PlatformPage } from './PlatformPage/PlatformPage';
export { default as AboutUsPage } from './AboutUsPage/AboutUsPage';
export { default as MarketInsightsPage } from './MarketInsightsPage/MarketInsightsPage';
export { default as ArticlePage } from './ArticlePage/ArticlePage';
export { default as TermsAndConditionsPage } from './TermsAndConditionsPage/TermsAndConditionsPage';
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage/PrivacyPolicyPage';
export { default as AgreementPage } from './AgreementPage/AgreementPage';
