import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import { Header, Footer } from '@/components/ui';

import '../sass/globals.scss';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700', '800'],
});

const roobert = localFont({
  src: [
    { path: './fonts/roobert/Roobert-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/roobert/Roobert-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/roobert/Roobert-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/roobert/Roobert-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './fonts/roobert/Roobert-Bold.woff2', weight: '700', style: 'normal' },
    { path: './fonts/roobert/Roobert-Heavy.woff2', weight: '800', style: 'normal' },
  ],
  variable: '--font-roobert',
  display: 'swap',
  preload: true,
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${inter.variable} ${roobert.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
